'use strict';
const width = 3;
const height = 5;
const area = width * height;
console.log(`value of area: ${area}`);
console.log(`typeof the area: ${typeof area}`);
const bill = 9.99;
const payment = 10.0;
const change = payment - bill;
console.log(`value of change: ${change}`);
console.log(`typeof the change: ${typeof change}`);
const quizzes = 80;
const midterm = 88;
const final = 99;
const grade = (quizzes + midterm + final) / 3;
console.log(`value of grade: ${grade}`);
console.log(`typeof the grade: ${typeof grade}`);
const firstName = 'William';
const lastName = 'Zhang';
const fullName = firstName + ' ' + lastName;
console.log(`value of fullName: ${fullName}`);
console.log(`typeof the fullName: ${typeof fullName}`);
const pH = 6;
const isAcidic = pH < 7;
console.log(`value of the isAcidic: ${isAcidic}`);
console.log(`typeof the isAcidic: ${typeof isAcidic}`);
const headCount = 9;
const isSparta = headCount === 300;
console.log(`value oof the isSparta: ${isSparta}`);
console.log(`typeof the isSparta: ${typeof isSparta}`);
let motto = fullName;
motto += ' is the GOAT';
console.log(`value of the motto: ${motto}`);
console.log(`typeof the motto: ${typeof motto}`);
